env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - prettier
plugins:
  - simple-import-sort
parserOptions:
  project:
    - tsconfig.json
  ecmaVersion: latest
  sourceType: module
rules:
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars': off
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  import/first: error
  import/newline-after-import: error
  import/no-duplicates: error
