env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - prettier
parserOptions:
  project:
    - tsconfig.json
  ecmaVersion: latest
  sourceType: module
rules:
  no-unused-vars: off
  "@typescript-eslint/no-unused-vars": off
